import { Inter } from "@next/font/google";

import "@/styles/global.css";
import "@/styles/reset.css";

import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const interFontFamily = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={interFontFamily.className}>
      <body className="container">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
